// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SMEFLOWSystem.Infrastructure.Data;

#nullable disable

namespace SMEFLOWSystem.Infrastructure.Migrations
{
    [DbContext(typeof(SMEFLOWSystemContext))]
    [Migration("20260429112534_UpdateAttendanceHRLogic")]
    partial class UpdateAttendanceHRLogic
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.BillingOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateTime>("BillingDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("BillingOrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("DiscountAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal?>("FinalAmount")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(19, 2)")
                        .HasComputedColumnSql("([TotalAmount]-[DiscountAmount])", true);

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Pending");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__BillingOrders__3214EC07");

                    b.HasIndex(new[] { "TenantId", "BillingOrderNumber" }, "UQ_BillingOrderNumber_Tenant")
                        .IsUnique();

                    b.ToTable("BillingOrders");
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.BillingOrderModule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<Guid>("BillingOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.Property<int?>("ProrationDays")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id")
                        .HasName("PK__BillingOrderModules__3214EC07");

                    b.HasIndex("BillingOrderId");

                    b.HasIndex("ModuleId");

                    b.ToTable("BillingOrderModules");
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Individual");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__Customer__3214EC07B17A5536");

                    b.HasIndex("TenantId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.DailyTimesheet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ExpectedShiftId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExpectedShiftSource")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsManuallyAdjusted")
                        .HasColumnType("bit");

                    b.Property<string>("ResolutionLogJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("StandardWorkingHours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SystemAnomalyFlag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TotalActualWorkedMinutes")
                        .HasColumnType("int");

                    b.Property<int>("TotalEarlyLeaveMinutes")
                        .HasColumnType("int");

                    b.Property<int>("TotalLateMinutes")
                        .HasColumnType("int");

                    b.Property<DateOnly>("WorkDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ExpectedShiftId");

                    b.ToTable("DailyTimesheets");
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.DailyTimesheetAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActionByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DailyTimesheetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DailyTimesheetId");

                    b.ToTable("DailyTimesheetAuditLogs");
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.DailyTimesheetSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ActualCheckIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ActualCheckOut")
                        .HasColumnType("datetime2");

                    b.Property<double?>("CheckInLatitude")
                        .HasColumnType("float");

                    b.Property<double?>("CheckInLongitude")
                        .HasColumnType("float");

                    b.Property<string>("CheckInSelfieUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("CheckOutLatitude")
                        .HasColumnType("float");

                    b.Property<double?>("CheckOutLongitude")
                        .HasColumnType("float");

                    b.Property<string>("CheckOutSelfieUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DailyTimesheetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EarlyLeaveMinutes")
                        .HasColumnType("int");

                    b.Property<int>("LateMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TargetShiftSegmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DailyTimesheetId");

                    b.ToTable("DailyTimesheetSegments");
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__Departme__3214EC070252CA08");

                    b.HasIndex("TenantId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<decimal>("BaseSalary")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("date");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("PositionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("ResignationDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Working");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__Employee__3214EC07C73E2C13");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("PositionId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.EmployeeShiftPattern", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("EffectiveEndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("EffectiveStartDate")
                        .HasColumnType("date");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ShiftPatternId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ShiftPatternId");

                    b.ToTable("EmployeeShiftPatterns");
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.Invite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("PositionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__Invites__3214EC07ABCDEF12");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("PositionId");

                    b.HasIndex("RoleId");

                    b.HasIndex("TenantId");

                    b.HasIndex(new[] { "Token" }, "UQ_Invite_Token")
                        .IsUnique();

                    b.ToTable("Invites");
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.LeaveRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LeaveType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("LeaveRequests", (string)null);
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.LeaveRequestSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("HoursRequested")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("LeaveDate")
                        .HasColumnType("date");

                    b.Property<Guid>("LeaveRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TargetShiftSegmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TargetShiftSegmentId");

                    b.HasIndex("LeaveRequestId", "TargetShiftSegmentId")
                        .IsUnique()
                        .HasDatabaseName("IX_LeaveRequestSegments_UniqueSegment");

                    b.ToTable("LeaveRequestSegments", (string)null);
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal>("MonthlyPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__Modules__3214EC07");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ShortCode")
                        .IsUnique();

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.ModuleSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__ModuleSubscriptions__3214EC07");

                    b.HasIndex("ModuleId");

                    b.HasIndex("TenantId", "ModuleId")
                        .IsUnique();

                    b.ToTable("ModuleSubscriptions");
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RecipientUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("General");

                    b.HasKey("Id")
                        .HasName("PK__Notifications__3214EC07");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Notifications_CreatedAt");

                    b.HasIndex("TenantId");

                    b.HasIndex("RecipientUserId", "IsRead")
                        .HasDatabaseName("IX_Notifications_RecipientUser_IsRead");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("DiscountAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal?>("FinalAmount")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(19, 2)")
                        .HasComputedColumnSql("([TotalAmount]-[DiscountAmount])", true);

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("OrderDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("OrderNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("New");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__Orders__3214EC0734CC9CEB");

                    b.HasIndex("CustomerId");

                    b.HasIndex(new[] { "TenantId", "OrderNumber" }, "UQ_OrderNumber_Tenant")
                        .IsUnique()
                        .HasFilter("[OrderNumber] IS NOT NULL");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("TotalPrice")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(29, 2)")
                        .HasComputedColumnSql("([Quantity]*[UnitPrice])", true);

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id")
                        .HasName("PK__OrderIte__3214EC0756359D82");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("LastError")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime?>("NextAttemptOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OccurredOnUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("RoutingKey")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK_OutboxMessages");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasDatabaseName("UX_OutboxMessages_EventId");

                    b.HasIndex("OccurredOnUtc")
                        .HasDatabaseName("IX_OutboxMessages_OccurredOnUtc");

                    b.HasIndex("Status", "NextAttemptOnUtc")
                        .HasDatabaseName("IX_OutboxMessages_Status_NextAttemptOnUtc");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("IX_OutboxMessages_TenantId_Status");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.OvertimeRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ApprovedHours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("OvertimeDate")
                        .HasColumnType("date");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("RequestedHours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal?>("SystemCalculatedMultiplier")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("OvertimeRequests");
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.PaymentTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid>("BillingOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Gateway")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("GatewayResponseCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GatewayTransactionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RawData")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BillingOrderId");

                    b.HasIndex("Gateway", "GatewayTransactionId")
                        .IsUnique();

                    b.ToTable("PaymentTransactions");
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.Payroll", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<int>("AbsentDays")
                        .HasColumnType("int");

                    b.Property<int>("ActualWorkingDays")
                        .HasColumnType("int");

                    b.Property<decimal>("BasePay")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("BaseSalarySnapshot")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("Bonus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("Deduction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("StandardWorkingDays")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Draft");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TotalEarlyLeaveMinutes")
                        .HasColumnType("int");

                    b.Property<int>("TotalLateMinutes")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalSalary")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Payrolls__3214EC07E77CFA45");

                    b.HasIndex("EmployeeId");

                    b.HasIndex(new[] { "TenantId", "EmployeeId", "Year", "Month" }, "UQ_Payroll_Month")
                        .IsUnique();

                    b.ToTable("Payrolls");
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__Position__3214EC07176C885B");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("TenantId");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.ProcessedEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("ConsumerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ProcessedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.HasKey("Id")
                        .HasName("PK_ProcessedEvents");

                    b.HasIndex("ProcessedAtUtc")
                        .HasDatabaseName("IX_ProcessedEvents_ProcessedAtUtc");

                    b.HasIndex("EventId", "ConsumerName")
                        .IsUnique()
                        .HasDatabaseName("UX_ProcessedEvents_EventId_Consumer");

                    b.ToTable("ProcessedEvents", (string)null);
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.RawPunchLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeviceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("bit");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("PunchType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SelfieUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "Timestamp")
                        .HasDatabaseName("IX_RawPunchLogs_Employee_Timestamp");

                    b.HasIndex("IsProcessed", "Timestamp")
                        .HasDatabaseName("IX_RawPunchLogs_IsProcessed_Timestamp");

                    b.ToTable("RawPunchLogs", (string)null);
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RevokeReason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__RefreshToken__3214EC07");

                    b.HasIndex("ReplacedByTokenId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "TenantId", "UserId" }, "IX_RefreshTokens_Tenant_User");

                    b.HasIndex(new[] { "TenantId", "TokenHash" }, "UQ_RefreshTokens_Tenant_TokenHash")
                        .IsUnique();

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("IsSystemRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Roles__3214EC07B3A63021");

                    b.HasIndex(new[] { "Name" }, "UQ__Roles__737584F671819C23")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.Shift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("GracePeriodMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsCrossDay")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.ShiftPattern", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CycleLengthDays")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("ShiftPatterns");
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.ShiftPatternDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DayIndex")
                        .HasColumnType("int");

                    b.Property<Guid?>("ScheduledShiftId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ShiftPatternId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ScheduledShiftId");

                    b.HasIndex("ShiftPatternId");

                    b.ToTable("ShiftPatternDays");
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.ShiftSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EndDayOffset")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StartDayOffset")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ShiftId");

                    b.ToTable("ShiftSegments");
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Active");

                    b.Property<DateOnly?>("SubscriptionEndDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__Tenants__3214EC0740A20BD5");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.TenantAttendanceSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<int>("CheckInRadiusMeters")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(100);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<TimeSpan>("DayStartCutOffTime")
                        .HasColumnType("time");

                    b.Property<int>("EarlyLeaveThresholdMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10);

                    b.Property<int>("LateThresholdMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10);

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<int>("MinimumOTMinutes")
                        .HasColumnType("int");

                    b.Property<int>("OTBlockMinutes")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly?>("WorkEndTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("WorkStartTime")
                        .HasColumnType("time");

                    b.HasKey("Id")
                        .HasName("PK__TenantAttendanceSetting__3214EC07");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("TenantAttendanceSettings");
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.TimesheetPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LockedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Year", "Month")
                        .IsUnique()
                        .HasDatabaseName("IX_TimesheetPeriods_Tenant_Year_Month");

                    b.ToTable("TimesheetPeriods", (string)null);
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__Users__3214EC07D3CEC114");

                    b.HasIndex(new[] { "TenantId", "Email" }, "UQ_Users_Email_Tenant")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.BillingOrderModule", b =>
                {
                    b.HasOne("SMEFLOWSystem.Core.Entities.BillingOrder", "BillingOrder")
                        .WithMany("BillingOrderModules")
                        .HasForeignKey("BillingOrderId")
                        .IsRequired()
                        .HasConstraintName("FK_BillingOrderModules_BillingOrders");

                    b.HasOne("SMEFLOWSystem.Core.Entities.Module", "Module")
                        .WithMany("BillingOrderModules")
                        .HasForeignKey("ModuleId")
                        .IsRequired()
                        .HasConstraintName("FK_BillingOrderModules_Modules");

                    b.Navigation("BillingOrder");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.Customer", b =>
                {
                    b.HasOne("SMEFLOWSystem.Core.Entities.Tenant", "Tenant")
                        .WithMany("Customers")
                        .HasForeignKey("TenantId")
                        .IsRequired()
                        .HasConstraintName("FK_Customers_Tenants");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.DailyTimesheet", b =>
                {
                    b.HasOne("SMEFLOWSystem.Core.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SMEFLOWSystem.Core.Entities.Shift", "ExpectedShift")
                        .WithMany()
                        .HasForeignKey("ExpectedShiftId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Employee");

                    b.Navigation("ExpectedShift");
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.DailyTimesheetAuditLog", b =>
                {
                    b.HasOne("SMEFLOWSystem.Core.Entities.DailyTimesheet", null)
                        .WithMany("AuditLogs")
                        .HasForeignKey("DailyTimesheetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.DailyTimesheetSegment", b =>
                {
                    b.HasOne("SMEFLOWSystem.Core.Entities.DailyTimesheet", null)
                        .WithMany("Segments")
                        .HasForeignKey("DailyTimesheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.Department", b =>
                {
                    b.HasOne("SMEFLOWSystem.Core.Entities.Tenant", "Tenant")
                        .WithMany("Departments")
                        .HasForeignKey("TenantId")
                        .IsRequired()
                        .HasConstraintName("FK_Departments_Tenants");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.Employee", b =>
                {
                    b.HasOne("SMEFLOWSystem.Core.Entities.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .HasConstraintName("FK_Employees_Departments");

                    b.HasOne("SMEFLOWSystem.Core.Entities.Position", "Position")
                        .WithMany("Employees")
                        .HasForeignKey("PositionId")
                        .HasConstraintName("FK_Employees_Positions");

                    b.HasOne("SMEFLOWSystem.Core.Entities.Tenant", "Tenant")
                        .WithMany("Employees")
                        .HasForeignKey("TenantId")
                        .IsRequired()
                        .HasConstraintName("FK_Employees_Tenants");

                    b.HasOne("SMEFLOWSystem.Core.Entities.User", "User")
                        .WithMany("Employees")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Employees_Users");

                    b.Navigation("Department");

                    b.Navigation("Position");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.EmployeeShiftPattern", b =>
                {
                    b.HasOne("SMEFLOWSystem.Core.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SMEFLOWSystem.Core.Entities.ShiftPattern", "ShiftPattern")
                        .WithMany()
                        .HasForeignKey("ShiftPatternId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("ShiftPattern");
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.Invite", b =>
                {
                    b.HasOne("SMEFLOWSystem.Core.Entities.Department", "Department")
                        .WithMany("Invites")
                        .HasForeignKey("DepartmentId")
                        .HasConstraintName("FK_Invites_Departments");

                    b.HasOne("SMEFLOWSystem.Core.Entities.Position", "Position")
                        .WithMany("Invites")
                        .HasForeignKey("PositionId")
                        .HasConstraintName("FK_Invites_Positions");

                    b.HasOne("SMEFLOWSystem.Core.Entities.Role", "Role")
                        .WithMany("Invites")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_Invites_Roles");

                    b.HasOne("SMEFLOWSystem.Core.Entities.Tenant", "Tenant")
                        .WithMany("Invites")
                        .HasForeignKey("TenantId")
                        .IsRequired()
                        .HasConstraintName("FK_Invites_Tenants");

                    b.Navigation("Department");

                    b.Navigation("Position");

                    b.Navigation("Role");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.LeaveRequest", b =>
                {
                    b.HasOne("SMEFLOWSystem.Core.Entities.User", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SMEFLOWSystem.Core.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovedByUser");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.LeaveRequestSegment", b =>
                {
                    b.HasOne("SMEFLOWSystem.Core.Entities.LeaveRequest", "LeaveRequest")
                        .WithMany("Segments")
                        .HasForeignKey("LeaveRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SMEFLOWSystem.Core.Entities.ShiftSegment", "TargetShiftSegment")
                        .WithMany()
                        .HasForeignKey("TargetShiftSegmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LeaveRequest");

                    b.Navigation("TargetShiftSegment");
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.ModuleSubscription", b =>
                {
                    b.HasOne("SMEFLOWSystem.Core.Entities.Module", "Module")
                        .WithMany("ModuleSubscriptions")
                        .HasForeignKey("ModuleId")
                        .IsRequired()
                        .HasConstraintName("FK_ModuleSubscriptions_Modules");

                    b.HasOne("SMEFLOWSystem.Core.Entities.Tenant", "Tenant")
                        .WithMany("ModuleSubscriptions")
                        .HasForeignKey("TenantId")
                        .IsRequired()
                        .HasConstraintName("FK_ModuleSubscriptions_Tenants");

                    b.Navigation("Module");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.Notification", b =>
                {
                    b.HasOne("SMEFLOWSystem.Core.Entities.User", "RecipientUser")
                        .WithMany()
                        .HasForeignKey("RecipientUserId")
                        .IsRequired()
                        .HasConstraintName("FK_Notifications_Users");

                    b.HasOne("SMEFLOWSystem.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .IsRequired()
                        .HasConstraintName("FK_Notifications_Tenants");

                    b.Navigation("RecipientUser");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.Order", b =>
                {
                    b.HasOne("SMEFLOWSystem.Core.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK_Orders_Customers");

                    b.HasOne("SMEFLOWSystem.Core.Entities.Tenant", "Tenant")
                        .WithMany("Orders")
                        .HasForeignKey("TenantId")
                        .IsRequired()
                        .HasConstraintName("FK_Orders_Tenants");

                    b.Navigation("Customer");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.OrderItem", b =>
                {
                    b.HasOne("SMEFLOWSystem.Core.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK_OrderItems_Orders");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.OutboxMessage", b =>
                {
                    b.HasOne("SMEFLOWSystem.Core.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_OutboxMessages_Tenants");
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.OvertimeRequest", b =>
                {
                    b.HasOne("SMEFLOWSystem.Core.Entities.User", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SMEFLOWSystem.Core.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovedByUser");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.PaymentTransaction", b =>
                {
                    b.HasOne("SMEFLOWSystem.Core.Entities.BillingOrder", null)
                        .WithMany()
                        .HasForeignKey("BillingOrderId")
                        .IsRequired();
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.Payroll", b =>
                {
                    b.HasOne("SMEFLOWSystem.Core.Entities.Employee", "Employee")
                        .WithMany("Payrolls")
                        .HasForeignKey("EmployeeId")
                        .IsRequired()
                        .HasConstraintName("FK_Payrolls_Employees");

                    b.HasOne("SMEFLOWSystem.Core.Entities.Tenant", "Tenant")
                        .WithMany("Payrolls")
                        .HasForeignKey("TenantId")
                        .IsRequired()
                        .HasConstraintName("FK_Payrolls_Tenants");

                    b.Navigation("Employee");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.Position", b =>
                {
                    b.HasOne("SMEFLOWSystem.Core.Entities.Department", "Department")
                        .WithMany("Positions")
                        .HasForeignKey("DepartmentId")
                        .IsRequired()
                        .HasConstraintName("FK_Positions_Departments");

                    b.HasOne("SMEFLOWSystem.Core.Entities.Tenant", "Tenant")
                        .WithMany("Positions")
                        .HasForeignKey("TenantId")
                        .IsRequired()
                        .HasConstraintName("FK_Positions_Tenants");

                    b.Navigation("Department");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.RawPunchLog", b =>
                {
                    b.HasOne("SMEFLOWSystem.Core.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.RefreshToken", b =>
                {
                    b.HasOne("SMEFLOWSystem.Core.Entities.RefreshToken", "ReplacedByToken")
                        .WithMany()
                        .HasForeignKey("ReplacedByTokenId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_RefreshTokens_ReplacedBy");

                    b.HasOne("SMEFLOWSystem.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .IsRequired()
                        .HasConstraintName("FK_RefreshTokens_Tenants");

                    b.HasOne("SMEFLOWSystem.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RefreshTokens_Users");

                    b.Navigation("ReplacedByToken");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.ShiftPatternDay", b =>
                {
                    b.HasOne("SMEFLOWSystem.Core.Entities.Shift", "ScheduledShift")
                        .WithMany()
                        .HasForeignKey("ScheduledShiftId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SMEFLOWSystem.Core.Entities.ShiftPattern", "ShiftPattern")
                        .WithMany("Days")
                        .HasForeignKey("ShiftPatternId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScheduledShift");

                    b.Navigation("ShiftPattern");
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.ShiftSegment", b =>
                {
                    b.HasOne("SMEFLOWSystem.Core.Entities.Shift", "Shift")
                        .WithMany("Segments")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.Tenant", b =>
                {
                    b.HasOne("SMEFLOWSystem.Core.Entities.User", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.TenantAttendanceSetting", b =>
                {
                    b.HasOne("SMEFLOWSystem.Core.Entities.Tenant", "Tenant")
                        .WithOne("AttendanceSetting")
                        .HasForeignKey("SMEFLOWSystem.Core.Entities.TenantAttendanceSetting", "TenantId")
                        .IsRequired()
                        .HasConstraintName("FK_TenantAttendanceSettings_Tenants");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.User", b =>
                {
                    b.HasOne("SMEFLOWSystem.Core.Entities.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .IsRequired()
                        .HasConstraintName("FK_Users_Tenants");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.UserRole", b =>
                {
                    b.HasOne("SMEFLOWSystem.Core.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_UserRoles_Roles");

                    b.HasOne("SMEFLOWSystem.Core.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_UserRoles_Users");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.BillingOrder", b =>
                {
                    b.Navigation("BillingOrderModules");
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.DailyTimesheet", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Segments");
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.Department", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Invites");

                    b.Navigation("Positions");
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.Employee", b =>
                {
                    b.Navigation("Payrolls");
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.LeaveRequest", b =>
                {
                    b.Navigation("Segments");
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.Module", b =>
                {
                    b.Navigation("BillingOrderModules");

                    b.Navigation("ModuleSubscriptions");
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.Position", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Invites");
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.Role", b =>
                {
                    b.Navigation("Invites");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.Shift", b =>
                {
                    b.Navigation("Segments");
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.ShiftPattern", b =>
                {
                    b.Navigation("Days");
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.Tenant", b =>
                {
                    b.Navigation("AttendanceSetting");

                    b.Navigation("Customers");

                    b.Navigation("Departments");

                    b.Navigation("Employees");

                    b.Navigation("Invites");

                    b.Navigation("ModuleSubscriptions");

                    b.Navigation("Orders");

                    b.Navigation("Payrolls");

                    b.Navigation("Positions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("SMEFLOWSystem.Core.Entities.User", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
