// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using SMEFLOWSystem.SharedKernel.Interfaces;
using System;
using System.Collections.Generic;

namespace SMEFLOWSystem.Core.Entities;

public partial class Attendance : ITenantEntity
{
    public Guid Id { get; set; }

    public Guid TenantId { get; set; }

    public Guid EmployeeId { get; set; }

    public DateOnly WorkDate { get; set; }

    public DateTime? CheckInTime { get; set; }

    public DateTime? CheckOutTime { get; set; }
    public double? CheckInLatitude { get; set; }
    public double? CheckInLongitude { get; set; }
    public double? CheckOutLatitude { get; set; }
    public double? CheckOutLongitude { get; set; }
    public string? CheckInSelfieUrl { get; set; }
    public string? CheckOutSelfieUrl { get; set; }
    public string Status { get; set; }

    public int? LateMinutes { get; set; }
    public int? EarlyLeaveMinutes { get; set; }
    public string? ApprovalStatus { get; set; }
    public Guid? ApprovedByUserId { get; set; }
    public string? ApprovalNotes { get; set; }
    public DateTime? ApprovedAt { get; set; }
    public string Notes { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual Tenant Tenant { get; set; }
}