// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using SMEFLOWSystem.SharedKernel.Interfaces;
using System;
using System.Collections.Generic;

namespace SMEFLOWSystem.Core.Entities;

public partial class Payroll : ITenantEntity
{
    public Guid Id { get; set; }

    public Guid TenantId { get; set; }

    public Guid EmployeeId { get; set; }

    public int Month { get; set; }

    public int Year { get; set; }

    public int StandardWorkingDays { get; set; }      // Số ngày công chuẩn trong tháng
    public int ActualWorkingDays { get; set; }        // Số ngày đi làm thực tế
    public int TotalLateMinutes { get; set; }         // Tổng phút đi trễ
    public int TotalEarlyLeaveMinutes { get; set; }   // Tổng phút về sớm
    public int AbsentDays { get; set; }               // Số ngày vắng mặt

    public decimal BaseSalarySnapshot { get; set; }   // Lương cơ bản snapshot
    public decimal BasePay { get; set; }              // Lương sau khi tính prorated (BaseSalary * tỷ lệ ngày làm)

    public decimal? Bonus { get; set; }               // Thưởng (Admin nhập tay)
    public decimal Deduction { get; set; }            // Tổng phạt (tự động tính từ late + early leave)

    public decimal TotalSalary { get; set; }          // Lương thực nhận cuối cùng

    public string Status { get; set; } = "Draft";     // Draft, Approved, Paid, Rejected

    public string? Notes { get; set; }                // Ghi chú (ví dụ: lý do phạt, thưởng)

    public DateTime? CreatedAt { get; set; }
    public DateTime? UpdatedAt { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual Tenant Tenant { get; set; }
}