// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using SMEFLOWSystem.SharedKernel.Interfaces;

namespace SMEFLOWSystem.Core.Entities;

public partial class UserRole : ITenantEntity
{
    public Guid UserId { get; set; }

    public Guid TenantId { get; set; }

    public int RoleId { get; set; }

    public virtual Role Role { get; set; }

    public virtual User User { get; set; }
}